config/routes.rb
Rails.application.routes.draw do

  resources :books do
    member do
      get :delete
    end
  end
  
  # get 'books/index'
  # get 'books/show'
  # get 'books/new'
  # get 'books/edit'
  # get 'books/delete'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.order('id ASC')
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash.alert = "Book has been created!"
      redirect_to(books_path)
    else
      render('new')
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash.alert = "Book has been updated!"
      redirect_to(books_path)
    else
      render('edit')
    end
  end

  def delete
    @book = Book.find(params[:id])
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash.alert = "Book has been deleted!"
    redirect_to(books_path)
  end

  private
  def book_params
    params.require(:book).permit(:title, :author, :genre, :price, :published_date)
  end
    

end

app/helpers/application_helper.rb
module ApplicationHelper

    def error_messages_for(object)
        render(:partial => 'application/error_messages', :locals => {:object => object})
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/application/_error_messages.html.erb
<% if object && object.errors.size > 0 %>
  <div id="error-explanation">
    <h2><%= pluralize(object.errors.size, "error") %> prohibited this record from being saved</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/books/_form.html.erb
<% error_messages_for(f.object) %>

<table summary="Book form fields">
    <tr>
        <th>Title</th>
        <td><%= f.text_field(:title) %></td>
    </tr>
    <tr>
        <th>Author</th>
        <td><%= f.text_field(:author) %></td>
    </tr>
    <tr>
        <th>Genre</th>
        <td><%= f.select(:genre, ["Action / Adventure", "Classics", "Comics", "Mystery", "Fantasy", "Historical Fiction", "Horror", "Literary Fiction", "Romance", "Science Fiction", "Non-fiction"]) %></td>
    </tr>
    <tr>
        <th>Price</th>
        <td><%= f.number_field(:price) %></td>
    </tr>
    <tr>
        <th>Published Date</th>
        <td><%= f.date_select(:published_date, :order => [:month, :day, :year], :start_year => Time.now.year-100) %></td>
    </tr>
</table>

app/views/books/delete.html.erb
<%= link_to('<button type="button"><< Back to List</button>'.html_safe, books_path, :class => 'back-link') %>

<div class="books delete">
  <h2>Delete Book</h2>

  <%= form_for(@book, :method => 'delete') do |f| %>

    <p>Are you sure you want to permanently delete this book?</p>
    <p><%= @book.title %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Book") %>
    </div>

  <% end %>
</div>

app/views/books/edit.html.erb
<%= link_to('<button type="button"><< Back to List</button>'.html_safe, books_path, :class => 'back-link') %>

<div class="books edit">
  <h2>Update Book</h2>

  <%= form_for(@book) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Update Book") %>
    </div>

  <% end %>
</div>

app/views/books/index.html.erb
<div class="books index">
  <h2>Book Collection</h2>
  <br>

  <% if flash[:alert] %>
      <div id="alert" style="color: green">
         <%= flash[:alert] %> 
      </div>
<% end %>

<br><br>

  <%= link_to('<button type="button">Add New Book</button>'.html_safe, new_book_path, :class => 'action new') %>

    <br><br>

  <table class="listing" summary="Book list">
    <tr class="header">
      <th>Title</th>
      <th>Author</th>
      <th>Genre</th>
      <th>Actions</th>
    </tr>
    <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.author %></td>
      <td><%= book.genre %></td>
      <td class="actions">
        <%= link_to('<button type="button">Show</button>'.html_safe, book_path(book), :class => 'action show') %>
        <%= link_to('<button type="button">Edit</button>'.html_safe, edit_book_path(book), :class => 'action edit') %>
        <%= link_to('<button type="button">Delete</button>'.html_safe, delete_book_path(book), :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/books/new.html.erb
<%= link_to('<button type="button"><< Back to List</button>'.html_safe, books_path, :class => 'back-link') %>

<div class="books new">
  <h2>Create Book</h2>

  <%= form_for(@book, :url => books_path, :method => 'post') do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Create Book") %>
    </div>

  <% end %>
</div>

app/views/books/show.html.erb
<%= link_to('<button type="button"><< Back to List</button>'.html_safe, books_path, :class => 'back-link') %>

<div class="books show">
  <h2>Show Book</h2>

  <table summary="Book detail view">
    <tr>
      <th>Title</th>
      <td><%= @book.title %></td>
    </tr>
    <tr>
      <th>Author</th>
      <td><%= @book.author %></td>
    </tr>
    <tr>
      <th>Genre</th>
      <td><%= @book.genre %></td>
    </tr>
    <tr>
      <th>Price</th>
      <td><%= @book.price %></td>
    </tr>
    <tr>
      <th>Published Date</th>
      <td><%= @book.published_date %></td>
    </tr>

    <tr>
      <th>Created</th>
      <td><%= @book.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @book.updated_at %></td>
    </tr>
  </table>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookcollection</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>